infinispan/cpp-client

include/infinispan/hotrod/Configuration.h, include/infinispan/hotrod/ConfigurationBuilder.h, include/infinispan/hotrod/ConfigurationChildBuilder.h, jni/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, jni/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, src/hotrod/impl/configuration/Configuration.cpp, src/hotrod/impl/operations/RetryOnFailureOperation.h, src/hotrod/impl/transport/TransportFactory.h, src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp, src/hotrod/impl/transport/tcp/TcpTransportFactory.h
https://issues.jboss.org/browse/HRCPP-198
=> HRCPP-198 Add infinispan.client.hotrod.max_retries equivalent

jni/pom.xml, jni/src/test/java/org/infinispan/client/jni/hotrod/CrossLanguageHotRodTest.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java
This updates the tests to 8.1.2
=> HRCPP-230 Updated test suite to 8.1.2. See also JDG-18

CMakeLists.txt, README.md, build.bat, proto/infinispan/hotrod/protobuf/base_types.proto, proto/org/infinispan/protostream/message-wrapping.proto, proto/org/infinispan/query/remote/client/query.proto
https://issues.jboss.org/browse/HRCPP-213
=> HRCPP-213 Add ProtoBuf generation machinery

include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/ExecuteCmdOperation.cpp, src/hotrod/impl/operations/ExecuteCmdOperation.h, src/hotrod/impl/operations/OperationsFactory.cpp, src/hotrod/impl/operations/OperationsFactory.h, test/Simple.cpp
expose query API based on vector<unsigned char> used by C#
=> Hrcpp 260/csharp queries

include/infinispan/hotrod/BasicMarshaller.h, include/infinispan/hotrod/JBasicMarshaller.h
This is a fix for https://issues.jboss.org/browse/HRCPP-320
=> HRCPP-320 # Fixed mem leak in marshaller

test/bin/server_ctl.py
Update exception handling syntax
Only pickle the process ID
=> HRCPP-330 Update server_ctl.py to work with Python 3

jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, jni/src/test/java/org/infinispan/client/jni/hotrod/CrossSiteFailoverTest.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java, test/SimpleTLS-SNI.cpp, test/data/standalone-hotrod-ssl.xml
Add SiteManualSwitchTest to JniTest
Add two more scenarios to SimpleTLS-SNI.cpp
=> HRCPP-340 Additional SNI and XSite tests

include/infinispan/hotrod/ProtoStreamMarshaller.h, include/infinispan/hotrod/QueryUtils.h, test/QueryTest.cpp
Fix for protobuf marshaller.
Solves: https://issues.jboss.org/browse/HRCPP-351 and https://issues.jboss.org/browse/HRCPP-352
=> HRCPP-351 # Fix get with protobuf

src/hotrod/sys/SSLSocket.cpp, src/hotrod/sys/SSLSocket.h, src/hotrod/sys/posix/Socket.cpp
Fix for https://issues.jboss.org/browse/HRCPP-354
plus a change in CertFindCertificateInStore to make the code compatible with Windows 7
=> Hrcpp 354/sslhang

include/infinispan/hotrod/CacheClientListener.h, src/hotrod/impl/operations/AbstractKeyOperation.h, src/hotrod/impl/operations/AbstractKeyValueOperation.h, src/hotrod/impl/operations/AddClientListenerOperation.cpp, src/hotrod/impl/operations/BulkGetKeysOperation.cpp, src/hotrod/impl/operations/BulkGetOperation.cpp, src/hotrod/impl/operations/ClearOperation.cpp, src/hotrod/impl/operations/ExecuteCmdOperation.cpp, src/hotrod/impl/operations/HotRodOperation.h, src/hotrod/impl/operations/PingOperation.cpp, src/hotrod/impl/operations/QueryOperation.h, src/hotrod/impl/operations/RemoveClientListenerOperation.cpp, src/hotrod/impl/operations/RemoveIfUnmodifiedOperation.cpp, src/hotrod/impl/operations/ReplaceIfUnmodifiedOperation.cpp, src/hotrod/impl/operations/SizeOperation.cpp, src/hotrod/impl/operations/StatsOperation.cpp
Fix for https://issues.jboss.org/browse/HRCPP-355
memory managements has been delegated to std libs (unique_ptr)
=> HRCPP-355 # Fixed and removed some tabs

src/hotrod/impl/NearRemoteCacheImpl.h
fixes: https://issues.jboss.org/browse/HRCPP-365
=> HRCPP-365 # Now near cache handles version correctly

test/data/standalone.xml
Fix for https://issues.jboss.org/browse/HRCPP-368
=> HRCPP-368 Updated standalone.xml

Jenkinsfile
This version of Jenkinsfile set up the PATH variable for build.sh script
=> Jenkinsfile with PATH

src/hotrod/sys/SSLSocket.cpp
fix to build with openssl 1.1
https://issues.jboss.org/browse/HRCPP-392
=> HRCPP-392 Build with openssl 1.1

CMakeLists.txt, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/GetAllOperation.cpp, src/hotrod/impl/operations/GetAllOperation.h, src/hotrod/impl/operations/OperationsFactory.cpp, src/hotrod/impl/operations/OperationsFactory.h, src/hotrod/impl/protocol/HeaderParams.cpp, src/hotrod/impl/transport/TransportFactory.h, test/Simple.cpp
This is a getAll implementation for C++.
https://issues.jboss.org/browse/HRCPP-405
=> Hrcpp 405/get all

test/ContinuousQueryTest.cpp
Fix for continuous queries test. When multiple CQ are running we need more synchronization stuff.
jira: https://issues.jboss.org/browse/HRCPP-408
=> HRCPP-408 Multi listener needs more synch stuff

.gitignore, CMakeLists.txt, Doxyfile.in, documentation/index.adoc
Updated documentation and code examples and added link to the generated API docs.
This should go with: https://github.com/infinispan/infinispan.github.io/pull/48
jira: https://issues.jboss.org/browse/HRCPP-271
=> HRCPP-271 Updated documentation and added api_docs

include/infinispan/hotrod/ConfigurationBuilder.h, include/infinispan/hotrod/NearCacheConfiguration.h, src/hotrod/impl/NearRemoteCacheImpl.h, src/hotrod/impl/RemoteCacheManagerImpl.cpp, xunit-test/NearCacheTest/CMakeLists.txt, xunit-test/NearCacheTest/NearCacheEvictionTest.cpp, xunit-test/NearCacheTest/NearCacheEvictionTest.h, xunit-test/NearCacheTest/NearCacheStaleReadsTest.cpp
This PR contains:
a test for the near cache evition
and some fixes on near cache tests
https://issues.jboss.org/browse/HRCPP-421
=> HRCPP-421 Near cache eviction test and misc fixes

jni/pom.xml, jni/src/main/java/org/infinispan/client/hotrod/RemoteCache.java, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, jni/src/main/swig/java.i, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java
Update java test suite to 9.1.1.Final
https://issues.jboss.org/browse/HRCPP-424
=> HRCPP-424 Updated test suite

Doxyfile.in, test/Simple.cpp
Remote execute test improved.
https://issues.jboss.org/browse/HRCPP-427
=> Hrcpp 427/remote exec args

include/infinispan/hotrod/RemoteCache.h, jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, jni/src/main/swig/java.i, jni/src/main/swig/std_future.i, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java
This is to enable RemoteAsyncAPITest class into the Swig test suite
https://issues.jboss.org/browse/HRCPP-432
=> Hrcpp 432/async swig

test/query_proto/addressbook.proto, test/query_proto/bank.proto, xunit-test/QueryTest/QueryTest.cpp
this fix the path for the protobuf generated files. With this the same include path i.e. "infinispan/hotrod/query.pb.h" works for the source repo and the rpm or zip.
https://issues.jboss.org/browse/HRCPP-439
=> HRCPP-439 Fix path for protobuf generate header

src/hotrod/impl/transport/tcp/TransportObjectFactory.cpp
Passing callback in the sasl_client_new method and fixing MD5 mech, we not send the initial response now (this makes java sasl happy).
https://issues.jboss.org/browse/HRCPP-445
=> HRCPP-445 Pass the callback in sasl_client_new and fix MD5

CMakeLists.txt, src/hotrod/impl/NearRemoteCacheImpl.h, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/AddClientListenerOperation.cpp, test/NearCacheFailoverTest.cpp, test/bin/server_ctl.py
fix for https://issues.jboss.org/browse/HRCPP-425
this is a replacement for
https://github.com/infinispan/cpp-client/pull/323
=> Hrcpp 425/new near cache fo test

Doxyfile.in, doxygen_main_page.txt, include/infinispan/hotrod/AuthenticationConfiguration.h, include/infinispan/hotrod/AuthenticationConfigurationBuilder.h, include/infinispan/hotrod/BasicMarshaller.h, include/infinispan/hotrod/ClientEvent.h, include/infinispan/hotrod/Configuration.h, include/infinispan/hotrod/ConfigurationBuilder.h, include/infinispan/hotrod/FailOverRequestBalancingStrategy.h, include/infinispan/hotrod/JBasicMarshaller.h, include/infinispan/hotrod/Marshaller.h, include/infinispan/hotrod/NearCacheConfiguration.h, include/infinispan/hotrod/ProtoStreamMarshaller.h, include/infinispan/hotrod/Query.h, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheManager.h, include/infinispan/hotrod/SecurityConfigurationBuilder.h, include/infinispan/hotrod/ServerConfigurationBuilder.h, include/infinispan/hotrod/SslConfigurationBuilder.h
Improved doxygen documentation.
https://issues.jboss.org/browse/HRCPP-451
=> Hrcpp 451/update apidoc

include/infinispan/hotrod/CounterEvent.h, include/infinispan/hotrod/Counters.h, src/hotrod/api/CountersImpl.cpp, src/hotrod/api/CountersImpl.h, src/hotrod/api/RemoteCounterManagerImpl.cpp, src/hotrod/impl/RemoteCounterManagerImpl.h, xunit-test/CountersTest/StrongCounterTest.cpp, xunit-test/CountersTest/WeakCounterTest.cpp
Don't copy the listener, use the one provided by the user instead.
https://issues.jboss.org/browse/HRCPP-472
=> HRCPP-472 Removed copy of the listener

src/hotrod/impl/event/EventDispatcher.cpp, src/hotrod/impl/operations/RetryOnFailureOperation.h
Fix for a correct handling of the counter exceptions
https://issues.jboss.org/browse/HRCPP-473
=> HRCPP-473 Fix for correct exception handling

CMakeLists.txt, include/infinispan/hotrod/RemoteCacheManager.h, include/infinispan/hotrod/RemoteCacheManagerAdmin.h, jni/pom.xml, jni/src/main/java/org/infinispan/client/hotrod/RemoteCache.java, jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdminImpl.java, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheUnsupported.java, jni/src/main/swig/java.i, jni/src/test/java/org/infinispan/client/jni/hotrod/CrossLanguageHotRodTest.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java, src/hotrod/api/RemoteCacheManager.cpp, src/hotrod/api/RemoteCacheManagerAdmin.cpp, src/hotrod/impl/RemoteCacheManagerImpl.cpp, src/hotrod/impl/RemoteCacheManagerImpl.h, src/hotrod/impl/operations/AdminOperation.h, src/hotrod/impl/operations/OperationsFactory.cpp, src/hotrod/impl/operations/OperationsFactory.h
Implementation for the cache admin operations
https://issues.jboss.org/browse/HRCPP-454
=> HRCPP-454 Admin operation

jni/pom.xml, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheUnsupported.java, jni/src/test/java/org/infinispan/client/jni/hotrod/CrossLanguageHotRodTest.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java
Update java swig test to 9.2.3.
https://issues.jboss.org/browse/HRCPP-474
=> HRCPP-474 Updated java test to 9.2.3

include/infinispan/hotrod/RemoteCacheManager.h, include/infinispan/hotrod/RemoteCacheManagerAdmin.h, jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, jni/src/main/swig/java.i, jni/src/main/swig/std_set.i, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java, src/hotrod/api/RemoteCacheManager.cpp, src/hotrod/api/RemoteCacheManagerAdmin.cpp
RemoteCacheManager.getCacheNames() implementation
https://issues.jboss.org/browse/HRCPP-475
=> Hrcpp 475/get cache names

include/infinispan/hotrod/Transactions.h, include/infinispan/hotrod/exceptions.h, src/hotrod/api/TransactionManager.cpp, src/hotrod/api/exceptions.cpp, xunit-test/TransactionTest/TransactionTest.cpp
commit() method now throws exception on rollback
https://issues.jboss.org/browse/HRCPP-479
=> HRCPP-479 commit throws exception on rollback

src/hotrod/api/TransactionManager.cpp
https://issues.jboss.org/browse/HRCPP-481
=> HRCPP-481 Fixed random gen setup

src/hotrod/sys/posix/Socket.cpp
https://issues.jboss.org/browse/HRCPP-482
=> HRCPP-482 EINTR signal handled with a retry

jni/pom.xml, jni/src/main/java/org/infinispan/client/hotrod/RemoteCache.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, jni/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java, jni/src/test/resources/test-is-primary-owner.js
Updated java test suite to 9.4.1.Final
https://issues.jboss.org/browse/HRCPP-474
=> HRCPP-474 Updated to 9.4.1.Final

src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.cpp, src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.h, src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp
HRCPP-485 fix backported on 8.1.x
=> Hrcpp 485/backport

CMakeLists.txt, include/infinispan/hotrod/CounterEvent.h, include/infinispan/hotrod/DataFormat.h, include/infinispan/hotrod/FailOverRequestBalancingStrategy.h, src/hotrod/api/RemoteCounterManagerImpl.cpp, src/hotrod/sys/posix/Socket.cpp
=> Fix build on MacOs

CMakeLists.txt
Add poolTest to the build_test target
=> HRCPP-499 configurable act on pool exhausted and test

Jenkinsfile, gtest-CMakeLists.txt.in, test/data/infinispan-ssl.xml
TLS with Infinispan 11.0.5+ works only if trustore is defined
=> TLS needs truststore to work with 11.0.5+

documentation/asciidoc/stories/assembly_compiling_protobuf.adoc, documentation/asciidoc/stories/assembly_installation.adoc, documentation/asciidoc/topics/ref_installation_prerequisites.adoc
=> [9.0] filter windows

documentation/asciidoc/stories/assembly_compiling_protobuf.adoc, documentation/asciidoc/stories/assembly_installation.adoc, documentation/asciidoc/topics/ref_installation_prerequisites.adoc
Conditionalize windows doc for downstream
=> filter windows

documentation/asciidoc/stories/assembly_compiling_protobuf.adoc, documentation/asciidoc/stories/assembly_installation.adoc, documentation/asciidoc/topics/ref_installation_prerequisites.adoc
=> Update docs to include win installation

xunit-test/PutGetTest/CMakeLists.txt
Fixed expected result for putGetTest: remove WILL_FAIL property
=> Fixed expected test result

CMakeLists.txt, gtest-CMakeLists.txt.in, src/hotrod/impl/TopologyInfo.cpp, src/hotrod/impl/TopologyInfo.h, src/hotrod/impl/transport/TransportFactory.h
Fix for https://issues.redhat.com/browse/HRCPP-504
=> Added syncro between trheads for topology. Fixes HRCPP-504

CMakeLists.txt, gtest-CMakeLists.txt.in, src/hotrod/impl/TopologyInfo.cpp, src/hotrod/impl/TopologyInfo.h, src/hotrod/impl/transport/TransportFactory.h
* Added syncro between trheads for topology. Fixes HRCPP-504
Backport from main
=> [9.1.x] Added syncro between trheads for topology. Fixes HRCPP-504 (#393)

src/hotrod/impl/operations/RetryOnFailureOperation.h, src/hotrod/impl/transport/TransportFactory.cpp, src/hotrod/impl/transport/TransportFactory.h, src/hotrod/impl/transport/tcp/ConnectionPool.cpp, src/hotrod/impl/transport/tcp/InetSocketAddress.cpp, src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.cpp, src/hotrod/sys/BlockingQueue.h, src/hotrod/sys/windows/Mutex.h
- moved failed servers set at TransportFactory level
- updated round robin strategy
- notify thread waiting on idle queue when busy queue changes
=> Notify waiting threads on idle queue when busy q changes

src/hotrod/impl/NearRemoteCacheImpl.h, src/hotrod/impl/event/EventDispatcher.cpp, src/hotrod/impl/operations/RetryOnFailureOperation.h, src/hotrod/impl/transport/TransportFactory.cpp, src/hotrod/impl/transport/TransportFactory.h, src/hotrod/impl/transport/tcp/ConnectionPool.cpp, src/hotrod/impl/transport/tcp/InetSocketAddress.cpp, src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.cpp, src/hotrod/sys/BlockingQueue.h, src/hotrod/sys/windows/Mutex.h, test/NearCacheFailoverTest.cpp
port of 9.1.x fix for better threads management.
=> Notify threads

.github/workflows/pr.yaml, Jenkinsfile, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, include/infinispan/hotrod/RemoteExecution.h, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/ExecuteCmdOperation.cpp, src/hotrod/impl/operations/ExecuteCmdOperation.h, src/hotrod/impl/operations/OperationsFactory.cpp, src/hotrod/impl/operations/OperationsFactory.h, test/Simple.cpp
added execute with key. The task will be executed on the node that owns the key.
```
/**
* Execute script on server
* \param name name of the script
* \param args maps of (name,value) arguments
* \param key a key used to target a specific node in the topology
* \return byte[] result in dark matter shape
*/
std::vector<unsigned char> execute(const std::string& name, const std::map<std::string, std::string>& args, const K& key)
{
return base_execute(&key, name, args);
}
/**
* Execute script on server
* \param name name of the script
* \param args maps of (name,value) arguments
* \param key a key used to target a specific node in the topology
* \return byte[] result in dark matter shape
*/
std::vector<unsigned char> execute(const std::string& name, const std::map<std::vector<char>, …
```
=> Execwithkey

.github/workflows/pr.yaml, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, include/infinispan/hotrod/RemoteExecution.h, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/ExecuteCmdOperation.cpp, src/hotrod/impl/operations/ExecuteCmdOperation.h, src/hotrod/impl/operations/OperationsFactory.cpp, src/hotrod/impl/operations/OperationsFactory.h, test/Simple.cpp
=> New exec with key operation

documentation/asciidoc/topics/proc_installing_client_nix.adoc, documentation/asciidoc/topics/ref_installation_prerequisites.adoc
Docs updates:
- os versions
- required compilers
- rpm repositories
=> HR CPP docs revision 9.2

documentation/asciidoc/topics/proc_installing_client_nix.adoc, documentation/asciidoc/topics/ref_installation_prerequisites.adoc
Backports #408 
Docs updates:
-     os versions
-     required compilers
-     rpm repositories
=> [9.2.x]HR CPP docs revision 9.2

documentation/asciidoc/topics/attributes/community-attributes.adoc, documentation/asciidoc/topics/proc_compiling_protobuf_nix.adoc, documentation/asciidoc/topics/proc_compiling_protobuf_win.adoc, documentation/asciidoc/topics/proc_installing_client_nix.adoc
docs fixes
fix syntax highlighting for code blocks, url to HR API docs
backports #407
=> [9.1.x]fix syntax highlighting for code blocks, url to HR API docs

documentation/asciidoc/topics/attributes/downstream-attributes.adoc
Updates version in downstream attribute file from 8.1 to 8.4
needs backport to 9.2.x
=> updates version in downstream attributes file

documentation/asciidoc/topics/attributes/downstream-attributes.adoc
backports #413 
Updates version in downstream attribute file from 8.1 to 8.4
=> [9.2.x]updates version in downtream attributes file
