infinispan/cpp-client

CMakeLists.txt
protobuf generated files are compiled into a separated library hotrod_protobuf
=> Removed protobuf source files in hotrod.so

CMakeLists.txt, include/infinispan/hotrod/ConfigurationBuilder.h, include/infinispan/hotrod/ConfigurationChildBuilder.h, include/infinispan/hotrod/ConnectionPoolConfigurationBuilder.h, include/infinispan/hotrod/ServerConfigurationBuilder.h, include/infinispan/hotrod/SslConfigurationBuilder.h, jni/src/main/swig/java.i, src/hotrod/impl/configuration/ConfigurationChildBuilder.cpp
This reintroduce the ConfigurationChildBuilder class into the ConfigurationBuilder hierarchy. The removal of this class (#231) has introduced unwanted API changes.
=> Hrcpp 309 - Restore ConfigurationChildBuilder class

CMakeLists.txt
defined
Only execute the target if HOTROD_PREBUILT_LIB_DIR is not defined
=> HRCPP-317 Skip the copyhrlibs target when HOTROD_PREBUILT_LIB_DIR is

include/infinispan/hotrod/RemoteCacheManager.h, src/hotrod/api/RemoteCacheManager.cpp, src/hotrod/impl/RemoteCacheManagerImpl.cpp, src/hotrod/impl/RemoteCacheManagerImpl.h, src/hotrod/impl/operations/RetryOnFailureOperation.h, src/hotrod/impl/transport/TransportFactory.h, src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp, src/hotrod/impl/transport/tcp/TcpTransportFactory.h
This is a fix for https://issues.jboss.org/browse/HRCPP-322.
Changed the RemoteCacheManager cluster switch method signatures to be equal with the Java ones
=> HRCPP-322 # Cluster switch methods now same as Java

include/infinispan/hotrod/JBasicMarshaller.h
This fixes a compiler error on windows (MSVC accept only compile time const as array size)
Fix for https://issues.jboss.org/browse/HRCPP-327
=> HRCPP-237 # Fix for MSVC error

include/infinispan/hotrod/Query.h, include/infinispan/hotrod/QueryUtils.h, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, proto/org/infinispan/query/remote/client/query.proto, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/operations/OperationsFactory.h, src/hotrod/impl/operations/QueryOperation.h, test/QueryTest.cpp
This adds querystring field and accessors to the QueryRequest class.
Backward compatibility is preserved (i.e. jpqlstring and accessors are still availables)
Fix for https://issues.jboss.org/browse/HRCPP-296
=> HRCPP-296 # added querystring methods

src/hotrod/api/RemoteCacheManager.cpp
DEFAULT_CLUSTER_NAME must be explicitly passed to the clusterSwitch method.
this is a fix for https://issues.jboss.org/browse/HRCPP-329
=> HRCPP-329 # fix for default switch

src/hotrod/sys/SChannelSocket.cpp, src/hotrod/sys/SChannelSocket.h
This PR enables clients to load .pem certificate from file.
If the serverCAFile property is not null, i.e.:
builder.ssl().serverCAFile("c:\path\to\certificate.pem")
the client will authenticate the server using that certificate as root certificate.
otherwise Windows certificate store is used. 
This is implements https://issues.jboss.org/browse/HRCPP-311
=> HRCPP-311 # Win client can now load .pem from file

include/infinispan/hotrod/RemoteCacheManager.h, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheManagerImpl.cpp, src/hotrod/impl/RemoteCacheManagerImpl.h, src/hotrod/impl/event/ClientListenerNotifier.cpp, src/hotrod/impl/event/ClientListenerNotifier.h, src/hotrod/impl/event/EventDispatcher.cpp, src/hotrod/impl/event/EventDispatcher.h, src/hotrod/impl/operations/AddClientListenerOperation.cpp, src/hotrod/impl/operations/AddClientListenerOperation.h, src/hotrod/impl/operations/RetryOnFailureOperation.h, src/hotrod/impl/transport/AbstractTransport.h, src/hotrod/impl/transport/Transport.h, src/hotrod/impl/transport/tcp/TcpTransport.cpp, src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp, src/hotrod/impl/transport/tcp/TcpTransportFactory.h, test/NearCacheTest.cpp
This PR fixes some memleaks reported by the command:
valgrind nearCacheTest
some of them refer to the events framework.
Related jira is:
https://issues.jboss.org/browse/HRCPP-341
=> HRCPP-341 # Fixed memleaks in nearCacheTest

CMakeLists.txt
HOTROD_PREBUILT_LIB_DIR is used
The main fix is on line 285. 
Also removed some tab characters in the file which accounts for the
other formatting changes.
=> HRCPP-348 Static Protobuf library is not found on Windows when

src/hotrod/sys/SChannelSocket.cpp, src/hotrod/sys/SChannelSocket.h, src/hotrod/sys/SSLSocket.cpp
Send close notify to peer in a SSL connection.
Fixes: https://issues.jboss.org/browse/HRCPP-347
=> Hrcpp 347/close notify

src/hotrod/sys/SSLSocket.cpp, test/QueryTest.cpp, test/SimpleTLS-SNI.cpp
Added resources release to the connect() method. 
Fixes for https://issues.jboss.org/browse/HRCPP-342
=> HRCPP-342 # Fixed memleaks on ssl test

include/infinispan/hotrod/BasicMarshaller.h, test/Simple.cpp
This extends BasicMarshaller to all the primitive types and generally to all the type that can be memcpyied.
https://issues.jboss.org/browse/HRCPP-346
=> HRCPP-346 # More type supported in BasicMarshaller

src/hotrod/impl/CustomClientListener.h, src/hotrod/impl/NearRemoteCacheImpl.h
Turned eager near cache to lazy. Plus some changes to remove compiler warning.
Fixes https://issues.jboss.org/browse/HRCPP-364
=> HRCPP-364 # lazy cache now

src/hotrod/sys/SChannelSocket.cpp
This PR changes the CertFindCertificateInStore call to be win7 compatible.
Fix for: https://issues.jboss.org/browse/HRCPP-369
=> HRCPP-369 Changed CertFindCertificateInStore for win7

build.bat
Maps a virtual drive to the build dir to shorten path and avoid problems on Windows
Relates to: https://issues.jboss.org/browse/HRCPP-372
=> HRCPP-372 map drive to shorten path

jni/pom.xml, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java
This updates C++ jni testsuite to 9.0.0.Final.
ClientAsymmetricClusterTest.java is no more included.
Relates to: 
https://issues.jboss.org/browse/HRCPP-371
=> HRCPP-371 Updated jar version and test

src/hotrod/impl/event/ClientListenerNotifier.cpp, src/hotrod/impl/event/ClientListenerNotifier.h, src/hotrod/impl/event/EventDispatcher.cpp, test/Events.cpp
changed code to cleanly release the event listener transport on listener remove and replaced mixed reference/pointer implementation with c++11 smart pointer.
Fixes: https://issues.jboss.org/browse/HRCPP-367
=> HRCPP-367 # fix plus code cleanup

src/hotrod/sys/posix/Socket.cpp
Cast tcp port to unsigned to prevent overflow.
Fixes: https://issues.jboss.org/browse/HRCPP-395
=> HRCPP-395 cast port to unsigned

src/hotrod/impl/transport/tcp/InetSocketAddress.cpp
port field initializer needs to be cast to unsigned to prevent overflow
fix for https://issues.jboss.org/browse/HRCPP-397
=> HRCPP-397 cast port to unsigned

test/NearCacheTest.cpp
fix for: 
https://issues.jboss.org/browse/HRCPP-398
=> HRCPP-398 Fix to catch randomic failure of manager.stop()

src/hotrod/impl/NearRemoteCacheImpl.h, src/hotrod/impl/RemoteCacheImpl.h, src/hotrod/impl/RemoteCacheManagerImpl.cpp, src/hotrod/impl/RemoteCacheManagerImpl.h
With this PR the client correctly remove all the listener for near cache when the cache manager is stopped.
https://issues.jboss.org/browse/HRCPP-403
=> HRCPP-403 Remove near cache listener when cm stops

jni/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, jni/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, jni/src/test/java/org/infinispan/client/jni/hotrod/JniTest.java, src/hotrod/impl/RemoteCacheManagerImpl.cpp
This PR contains changes on the swig wrapper that remove some of expected failure in the java test list.
Plus a fix on the client that now correctly set the force return value flag in the request.
https://issues.jboss.org/browse/HRCPP-390
=> Hrcpp 390/rm some expected fail

src/hotrod/impl/operations/ExecuteCmdOperation.cpp, test/Simple.cpp
Fix for https://issues.jboss.org/browse/HRCPP-417
=> HRCPP-411 Fixed args passing for remote exec

src/hotrod/impl/operations/ContainsKeyOperation.cpp, src/hotrod/impl/operations/GetOperation.cpp, src/hotrod/impl/operations/GetWithMetadataOperation.cpp, src/hotrod/impl/operations/GetWithVersionOperation.cpp, src/hotrod/impl/operations/QueryOperation.h
OK response code 0x06 (compatibility mode enable) was intended as an error.
fix for https://issues.jboss.org/browse/HRCPP-418
=> HRCPP-418 correct response status processing

include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, src/hotrod/api/RemoteCacheBase.cpp
Add a new execute() method that accept map of std::vector<char> key and value as arguments for the remote script.
https://issues.jboss.org/browse/HRCPP-412
=> HRCPP-412 Added execute() method swig friendly

CMakeLists.txt, include/infinispan/hotrod/BasicTypesProtoStreamMarshaller.h, include/infinispan/hotrod/ProtoStreamMarshaller.h, include/infinispan/hotrod/Query.h, jni/swig.cmake, proto/infinispan/hotrod/protobuf/base_types.proto, proto/org/infinispan/protostream/message-wrapping.proto, proto/org/infinispan/query/remote/client/query.proto, src/hotrod/impl/protocol/Codec20.cpp, xunit-test/ClearTest/CMakeLists.txt, xunit-test/NearCacheTest/CMakeLists.txt, xunit-test/PutGetTest/CMakeLists.txt, xunit-test/QueryTest/CMakeLists.txt, xunit-test/QueryTest/QueryTest.cpp
https://issues.jboss.org/browse/HRCPP-436
This adds two new target for the build:
- build_dist
- build_test
The intended use is as follows.
**Build the distribution pack**
no need for maven or gtest
cd build
cmake ..
cmake --build . --target build_dist
cpack
**Build test against prebuilt**
no need for the full build
cd build
cmake .. -DHOTROD_JBOSS_HOME=&lt;path to jboss&gt; -DHOTROD_PREBUILT_LIB_DIR=&lt;path to the client libs&gt;
cmake --build . --target build_test
ctest -V
If you want to use your system protobuf libraries you can add -DHR_USE_SYSTEM_PROTOBUF=ON to the cmake setup
=> Hrcpp 436/new cmake targets

src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp, src/hotrod/sys/SChannelSocket.cpp
Correctly process error related to TLS certificates on windows.
Fix for: https://issues.jboss.org/browse/HRCPP-434
=> HRCPP-434 Fix TLS certificate error handling

include/infinispan/hotrod/JBasicMarshaller.h, include/infinispan/hotrod/JBossMarshaller.h, include/infinispan/hotrod/RemoteCache.h, include/infinispan/hotrod/RemoteCacheBase.h, include/infinispan/hotrod/RemoteExecution.h, jni/src/main/swig/java.i, src/hotrod/api/RemoteCacheBase.cpp, src/hotrod/impl/RemoteCacheImpl.cpp, src/hotrod/impl/RemoteCacheImpl.h, test/Simple.cpp
Improvement of the remote execute interface. Now user can pass arguments and call remote execution without having to directly deal with marshaller.
https://issues.jboss.org/browse/HRCPP-435
Example:
`
std::string script("// mode=local, language=javascript, parameters=[keyValue, keyName, num]\n"
"var cache = cacheManager.getCache(\"namedCache\");\n"
"cache.put(\"a\", keyValue);\n"
"cache.put(\"b\", \"b\");\n"
"cache.get(keyName);\n"
"num;\n");
RemoteExecution<> execution = cache.getRemoteExecution();
execution.putScript("script.js", script);
execution.addArg("keyValue", "abc");
execution.addArg("keyName", "a");
execution.addArg("num", 2);
int* ret = execution.template execute<int*>("script.js");
`
=> HRCPP-435 Improved remote execute usability

src/hotrod/impl/NearRemoteCacheImpl.h, src/hotrod/impl/RemoteCacheManagerImpl.cpp, src/hotrod/impl/event/ClientListenerNotifier.cpp, src/hotrod/impl/event/ClientListenerNotifier.h, src/hotrod/impl/event/EventDispatcher.cpp, src/hotrod/impl/event/EventDispatcher.h, src/hotrod/impl/operations/AddClientListenerOperation.cpp, src/hotrod/impl/operations/AddClientListenerOperation.h, src/hotrod/impl/operations/RemoveClientListenerOperation.cpp, src/hotrod/impl/transport/tcp/TcpTransport.cpp, test/ContinuousQueryTest.cpp, xunit-test/NearCacheTest/NearCacheEvictionTest.cpp, xunit-test/NearCacheTest/NearCacheStaleReadsTest.cpp
This PR fixes handling of the transport instance when an add listener operation fails. 
Also added fixes for some race condition in the near cache implementation
https://issues.jboss.org/browse/HRCPP-429
https://issues.jboss.org/browse/HRCPP-446
=> HRCPP-429 Fixed Transport handling on error

CMakeLists.txt, jni/swig.cmake, src/hotrod/impl/transport/tcp/TransportObjectFactory.cpp
Solves https://issues.jboss.org/browse/HRCPP-466
=> HRCPP-466 Improved error handling

CMakeLists.txt, Jenkinsfile, gtest-CMakeLists.txt.in, xunit-test/ClearTest/CMakeLists.txt, xunit-test/CountersTest/CMakeLists.txt, xunit-test/NearCacheTest/CMakeLists.txt, xunit-test/PutGetTest/CMakeLists.txt, xunit-test/QueryTest/CMakeLists.txt, xunit-test/TransactionTest/CMakeLists.txt
Last version of googletest fails on CI.
This PR updates the googletest integration and fix the build.
Relevant fix is on Jenkinsfile
https://issues.jboss.org/browse/HRCPP-483
=> fix googletest build on CI

src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.cpp, src/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.h, src/hotrod/impl/transport/tcp/TcpTransportFactory.cpp
Removed locks in the TcpTransportFactory because deadlock with the mutex in BlockingQueue class
https://issues.jboss.org/browse/HRCPP-485
=> HRCPP-485 Removed unnecessary mutex lock

CMakeLists.txt, jni/swig.cmake
cmake configuration now continues if googletest can't be build.
https://issues.jboss.org/browse/HRCPP-489
=> HRCPP-489 No fail if googletest has problems

src/hotrod/impl/consistenthash/SegmentConsistentHash.h
Fix for topology segment size evaluation on windows.
https://issues.jboss.org/browse/HRCPP-493
=> HRCPP-493 Fix topology segment size evaluation

CMakeLists.txt, cmake-modules/CodeCoverage.cmake
This PR allows user to get code coverage of the test suite (ctest execution).
How to:
1. Generate the require makefile target with
`mkdir build && cd build && cmake -DHOTROD_JBOSS_HOME=<ispn home> -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE= ..`
1. Build the wanted target:
`cmake --build . --target hotrod_coverage_html` for html output
`cmake --build . --target hotrod_coverage_xml` for xml output
Both the targets will run the test suite and collect coverage data. Work only for linux GCC
https://issues.jboss.org/browse/HRCPP-490
=> HRCPP-490 Added two new targets to get code coverage info

CMakeLists.txt, include/infinispan/hotrod/JBossMarshaller.h, include/infinispan/hotrod/exceptions.h, jni/pom.xml, src/hotrod/impl/transport/tcp/ConnectionPool.cpp, src/hotrod/sys/BlockingQueue.h, test/PoolTest.cpp, test/PoolUnitTest.cpp
This allows the user to configure the recover policy when connection pool is exhausted:
configurationBuilder.connectionPool().exhaustedAction(WAIT)
waits indefinitely for a connection to be returned and made available
configurationBuilder.connectionPool().exhaustedAction(EXCEPTION)
raises a NoSuchElementException
=> HRCPP-499 configurable act on pool exhausted and test

include/infinispan/hotrod/Query.h
This fixes HRCPP-501.
Inheritance has been replaced with delegation for QueryRequest.
See jira ticket for more details
=> Fix for HRCPP-501

include/infinispan/hotrod/TransactionManager.h, src/hotrod/api/TransactionManager.cpp
not exported method must not be used in header file.
=> fix unresolved external

include/infinispan/hotrod/Query.h, proto/org/infinispan/query/remote/client/query.proto, src/hotrod/api/RemoteCacheBase.cpp
A new field `local` has been added to the QueryRequest class server  side.
This PR:
- sync .proto definition with the java one
- sets default value for local on the client side
- updates method base_query_char (used by C#)
=> Updated QueryRequest structure

CMakeLists.txt, Jenkinsfile, prebuilt-tests/centos7/Dockerfile, prebuilt-tests/centos8/Dockerfile, test/data/infinispan-sasl-ssl.xml, test/data/infinispan-ssl.xml
fixed cmake to run infinispan with tls1.2 when openssl<1.1.1
plus aligned Dockerfile with downstream
=> fix for jdk 11 and openssl < 1.1.1

documentation/asciidoc/topics/attributes/community-attributes.adoc, documentation/asciidoc/topics/proc_compiling_protobuf_nix.adoc, documentation/asciidoc/topics/proc_compiling_protobuf_win.adoc, documentation/asciidoc/topics/proc_installing_client_nix.adoc
Small fixes:
- Fix attribute with url to HR C++ api docs
- remove "bash" from code block annotations (this caused issue with syntax highlighting, the commands starting with # were commented out)
Can be merged
=> Minor docs fixes
